### ISSUE TITLE
how to save chain data outside of the container, 

### ISSUE THREAD

**Issue by moda20** [varnav/binance-node-docker#17]
Do we lose the chain data after shutting down the container ?, how can I save it, in which folder it is saved inside the container?

**Comment by varnav** [comment]
No, you're not supposed to lose data as it's saved in the volume.

**Comment by moda20** [comment]
is there a way to save the data outside of the container ?

**Comment by varnav** [comment]
Data is saved in the volume outside of the container.

https://github.com/varnav/binance-node-docker/blob/master/Dockerfile#L47

**Comment by moda20** [comment]
yes, that is in the dockerFile, i am trying to use this with a compose file 
```
bnbnode:
    image : varnav/binance-node
    container_name: bnbnode
    ports:
      - 27146:27146
      - 27147:27147
    volumes:
      - bnb:/var/lib/bnb/
    networks:
      - bnb
    environment:
      BNET: "prod"
    security_opt:
      - no-new-privileges
    sysctls:
      net.core.somaxconn: 4096
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "1"
        
```

i am replicating the compose file in this repository. if i do it like above where will the data be saved outside the container ? is the data inside the container found in /var/lib/bnb or in /home/bnbchain/.bnbchain ?
